# @author Will Eaton

services:
  # ---------------------------
  # DATABASE SERVICES
  # ---------------------------
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nicewill
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: nicewill
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  redis:
    image: redis:7
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  mongo:
    image: mongo:7
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: nicewill
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  # ---------------------------
  # PYTHON GRAPHQL BACKEND
  # ---------------------------
  backend:
    build: ./backend
    container_name: python-backend
    restart: always
    depends_on:
      - mysql
      - redis
      - mongo
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: nicewill
      MYSQL_DB: mysql

      REDIS_HOST: redis

      MONGO_HOST: mongo
      MONGO_USER: admin
      MONGO_PASSWORD: nicewill

volumes:
  mysql_data:
  redis_data:
  mongo_data:
