# @author Will Eaton

services:
  # ---------------------------
  # DATABASE SERVICES
  # ---------------------------
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10


#  redis:
#    image: redis:7
#    container_name: redis-container
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data


#  mongo:
#    image: mongo:7
#    container_name: mongo-container
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo_data:/data/ER Implementation + Fake Data


  # ---------------------------
  # PYTHON GRAPHQL BACKEND
  # ---------------------------
  backend:
    build: ./backend
    container_name: python-backend
    restart: always
    depends_on:
      - mysql
#      - mongo
    ports:
      - "8001:8000"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_ENDPOINT: ${REDIS_ENDPOINT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      MONGO_HOST: ${MONGO_HOST}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"

volumes:
  mysql_data:
#  mongo_data:
